services:
  # 1. The Database Engine
  postgres:
    image: postgres:15
    container_name: agriflow_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: agriflow_dw
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agriflow_net

  # 2. The Interface (pgAdmin) - Optional if you have it installed locally, 
  # but good to have in the container for consistency.
  pgadmin:
    image: dpage/pgadmin4
    container_name: agriflow_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@agriflow.com
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - agriflow_net

volumes:
  postgres_data:

networks:
  agriflow_net:
    driver: bridge